[[redirects]]
  from = “/api/*”
  to = “https://spenndify-expenses-tracker-app.herokuapp.com/spendy/user/authenticate:splat"
  status = 200
[[redirects]]
  from = “/*”
  to = “/index.html”
  status = 200