[[redirects]]
  from = "/Login"
  to = "https://spenndify-expenses-tracker-app.herokuapp.com/spendy/user/authenticate"
  status = 200
 
 # These are optional
  force = true
  headers = {X-From = "Netlify"}